### ISSUE TITLE
How to run server

### ISSUE THREAD

**Issue by asbaghel** [Pratiknarola/AgroMarket#12]
![image](https://user-images.githubusercontent.com/46319981/127340097-3ac0b666-209f-4c12-876b-10443243b725.png)
After npm install , npm start i am getting this error in server How should i resolve it

**Comment by Pratiknarola** [comment]
Are you using local mongoDB server or mongodb atlas?

**Comment by asbaghel** [comment]
Thanks😊 Now it is working I didn't change URI.

When we create a new user its it is  asking for secretOrPrivateKey must have a value . secretOrPrivateKey  is not a field in sign up form

![image](https://user-images.githubusercontent.com/46319981/127444417-bd203bcd-49de-4113-bb56-a4460affc803.png)

**Comment by asbaghel** [comment]
Which auction algorithm is being used in this application?
